/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olc1.project1;

import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import olc1.project1.errors.LexicalError;
import olc1.project1.errors.SintaxError;

/**
 *
 * @author Xhunik
 */
public class ErrorFrame extends javax.swing.JFrame {
    LinkedList<LexicalError> lexErrors;
    LinkedList<SintaxError> sintaxErrors;
    /**
     * Creates new form ErrorFrame
     * @param lexErrors
     * @param sintaxErrors
     */
    public ErrorFrame(LinkedList<LexicalError> lexErrors, LinkedList<SintaxError> sintaxErrors) {
        initComponents();
        this.lexErrors = lexErrors;
        this.sintaxErrors = sintaxErrors;
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        DefaultTableModel model = new DefaultTableModel(null, new Object[] {"#", "Tipo", "Lexema", "Fila", "Columna"});
        int i = 0;
        for (SintaxError sintaxError : sintaxErrors) {
            i++;
            model.addRow(new Object[] {i, "Sintactico" ,sintaxError.lexema, sintaxError.row, sintaxError.col});
        }
        
        for (LexicalError lexError : lexErrors) {
            i++;
            model.addRow(new Object[] {i, "Lexico" ,lexError.lexema, lexError.row, lexError.col});
        }
        this.jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Tipo", "Lexema", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
